NumParticles: 1000
ParticleMass: 1.0
ParticleSize: 5
FluidTargetDensity: 1.0
GravityStrength: 1.0
RandomSeed: 0
SmoothingKernelRadius: 1.0
PressureKernelExponent: 2
NearPressureKernelExponent: 4
SimulationWidth: 1024
SimulationHeight: 512
SimulationPadding: 10
FramesPerSecond: 60
SpatialHashingBins: -1 